### ISSUE TITLE
discord rich presence not working on new ui intellij

### ISSUE THREAD

**Issue by klnknx** [Almighty-Alpaca/JetBrains-Discord-Integration#260]
`Unhandled exception in [StandaloneCoroutine{Cancelling}@7b8c1fe6, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7b8c1fe6, Dispatchers.Default]
`

**Comment by thewinner958** [comment]
Yeah kinda the same issue for me, although I don't see an error log when I launch it

**Comment by holo-lb** [comment]
Same issue here, stacktrace for debugging:

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@5a5e5539, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5a5e5539, Dispatchers.Default]

```

**Comment by imandings** [comment]
Same here!

**Comment by oravagamer** [comment]
Same

**Comment by TallonRain** [comment]
Same.

`Unhandled exception in [StandaloneCoroutine{Cancelling}@7e8175e9, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7e8175e9, Dispatchers.Default]
`

**Comment by vincent-hsaalen** [comment]
Can confirm.
For me it works perfectly on Rider version 2022.3 but when enabling the new User Interface it does not connect to my discord client at all.

**Comment by cleversonlira** [comment]
Same here.
Works on Jetbrains Webstorm with new UI, up to version 2022.2.
After updating to 2022.3 it broke

**Comment by Alienlive145332** [comment]
same

**Comment by Nyde42** [comment]
Same here, with basically the same StackTrace that @TRAN-Ki posted.

**Comment by timka-123** [comment]
same, pycharm community edition 2022.3, new ui.
trace:
```
java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5f0d4b85, Dispatchers.Default]
```

**Comment by NightDev701** [comment]
Same

**Comment by qe7** [comment]
Just gonna comment same until we get an answer.

Same.

**Comment by lukasvdgaag** [comment]
It does not work from version 2022.3 and upwards. If you want to use the Discord Integration plugin, you will need to stick to any version lower than that (e.g. 2022.2.x) because it will work for those versions. The developers said in their Discord that they are working on a fix, which will release soon. Until then, there is no use to keep commenting that it does not work. So for now, downgrade (or don't update) if you want to use it, otherwise wait for the developers to fix it.
And if you find this to be taking too long, you can always fork the project and try to fix it yourself.

**Comment by Nyde42** [comment]
@lukasvdgaag I think everyone here is well aware that the problem only exists on 2022.3 and upwards. However, the purpose of everyone commenting is to draw more attention to this issue, because as it stands right now, no developer has reacted to this issue whatsoever. It's great to hear that they're working on a fix, but since only a fraction of the people here are on the Discord, how are we supposed to know? See what I mean? If we only look at this issue page, it would appear that the devs simply have not noticed yet, so people keep commenting to **make** them notice. I'm pretty sure if the issue had a comment by a dev, or an assignee, or **anything**, a lot of people (including me) wouldn't have felt the necessity to post a comment at all.

This is not supposed to be me complaining about the devs not reacting to this issue on GitHub, I'm just glad to hear that they're working on it, I'm just explaining why I think your comment is missing the point.

**Comment by rekkisomo** [comment]
This is still happening, though there's a weird workaround (at least, for me). Wasn't connecting to Discord at all, but when i t did, it wasn't doing any render updates and not throwing errors. Disabling the new UI and then enabling it again seems to fix it???

**Comment by dnbln** [comment]
> This is still happening, though there's a weird workaround (at least, for me). Wasn't connecting to Discord at all, but when i t did, it wasn't doing any render updates and not throwing errors. Disabling the new UI and then enabling it again seems to fix it???

@rekkisomo This was fixed in #265. Are you sure you're on 1.11.0?

**Comment by rekkisomo** [comment]
> > This is still happening, though there's a weird workaround (at least, for me). Wasn't connecting to Discord at all, but when i t did, it wasn't doing any render updates and not throwing errors. Disabling the new UI and then enabling it again seems to fix it???
> 
> @rekkisomo This was fixed in #265. Are you sure you're on 1.11.0?

I am, so I guess it's happening again? I've tried clean installing the plugin as well as IntelliJ to no avail.

**Comment by TheDesignCraftYT** [comment]
Got those 2 exceptions with v1.11.0
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@6c44a85, Dispatchers.Default]

java.io.FileNotFoundException: \\?\pipe\discord-ipc-0 (Alle Pipeinstanzen sind ausgelastet)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.connect(WindowsSocket.kt:23)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6c44a85, Dispatchers.Default]
```
```
kotlin.UninitializedPropertyAccessException: lateinit property randomAccessFile has not been initialized
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.close(WindowsSocket.kt:28)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.disconnect(SocketHandler.kt:67)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.disconnect(KDiscordIPC.kt:118)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.disconnectInternal(DiscordIpcConnection.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.dispose(DiscordIpcConnection.kt:81)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:243)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:231)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
so ig this bug isn't fixed with 1.11.0?

**Comment by TheDesignCraftYT** [comment]
Now it's working for me 🤷‍♂️
