### ISSUE TITLE
Plugin doesn't work in 2021.3, throws NoSuchMethodError

### ISSUE THREAD

**Issue by NetherGranite** [Almighty-Alpaca/JetBrains-Discord-Integration#212]
Upon updating to Rider 2021.3, this exception is now regularly thrown by this plugin, and the plugin doesn't work for me.

```
java.lang.NoSuchMethodError: 'java.lang.String com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.fileEditor.impl.EditorWindow)'
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:112)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:52)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt.resumeWithAction(async.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt$invokeSuspendingOn$$inlined$suspendCoroutine$lambda$1.run(async.kt:54)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:188)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$ModalContext.dispose(RiderModalPopupCookie.kt:63)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:136)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:166)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:157)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$Companion.using(RiderModalPopupCookie.kt:98)
	at com.jetbrains.rider.intentions.altEnter.RiderShowIntentionActionsHandler$Companion.k(RiderShowIntentionActionsHandler.kt:131)
	at com.jetbrains.rider.intentions.altEnter.RiderShowIntentionActionsHandler$Companion.access$showPopup(RiderShowIntentionActionsHandler.kt:42)
	at com.jetbrains.rider.intentions.altEnter.RiderShowIntentionActionsHandler$Companion$showAltEnterMenu$1$2.accept(RiderShowIntentionActionsHandler.kt:87)
	at com.jetbrains.rider.intentions.altEnter.RiderShowIntentionActionsHandler$Companion$showAltEnterMenu$1$2.accept(RiderShowIntentionActionsHandler.kt:42)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:103)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:149)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory$processProtocolModel$4.invoke(ReSharperBulbMenuModelFactory.kt:141)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory$processProtocolModel$4.invoke(ReSharperBulbMenuModelFactory.kt:33)
	at com.jetbrains.rd.util.reactive.BoolPropertyExKt$whenTrue$1.invoke(BoolPropertyEx.kt:12)
	at com.jetbrains.rd.util.reactive.BoolPropertyExKt$whenTrue$1.invoke(BoolPropertyEx.kt)
	at com.jetbrains.rd.util.reactive.IPropertyBase$view$$inlined$let$lambda$1.invoke(Interfaces.kt:78)
	at com.jetbrains.rd.util.reactive.IPropertyBase$view$$inlined$let$lambda$1.invoke(Interfaces.kt:62)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.OptProperty.set(Property.kt:40)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.onWireReceived(RdProperty.kt:76)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:50)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker.invoke(MessageBroker.kt:49)
	at com.jetbrains.rd.framework.MessageBroker.access$invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.MessageBroker$dispatch$$inlined$lock$lambda$1.invoke(MessageBroker.kt:105)
	at com.jetbrains.rd.framework.MessageBroker$dispatch$$inlined$lock$lambda$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:72)
	at com.jetbrains.rd.platform.protocol.IRdDispatcherKt.pumpProtocolQueue(IRdDispatcher.kt:27)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory.F(ReSharperBulbMenuModelFactory.kt:144)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory.access$processProtocolModel(ReSharperBulbMenuModelFactory.kt:33)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory$create$5.invoke(ReSharperBulbMenuModelFactory.kt:75)
	at com.jetbrains.rider.intentions.altEnter.ReSharperBulbMenuModelFactory$create$5.invoke(ReSharperBulbMenuModelFactory.kt:33)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:27)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.Property.setValue(Property.kt:20)
	at com.jetbrains.rd.util.reactive.Property.set(Property.kt:13)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.onWireReceived(RdProperty.kt:76)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

A quick search turns up [this list of breaking IntelliJ API changes](https://plugins.jetbrains.com/docs/intellij/api-changes-list-2021.html#intellij-platform-20213), and it reveals that the method this plugin attempts to call that throws this error has had its last parameter removed:

> `com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(Project, VirtualFile, EditorWindow)` method parameter `EditorWindow` removed
>
> This parameter was never needed, but led to code coupling.

**Comment by NetherGranite** [comment]
Sorry, just discovered that my IDE is silently failing to update plugins.
